#!/bin/bash

EXE=$0
while [ -L "$EXE" ]; do
      EXE=`readlink $EXE`
done
BASE=`dirname $EXE`
BASE=`cd $BASE; pwd`

if [ `uname` == "Darwin" ]; then
    export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/soylatte16-i386-1.0.3/
    export ALT_BOOTDIR=$JAVA_HOME
else
    export ALT_BOOTDIR=/usr/lib/jvm/java-6-sun/
fi

if [ "$MAKE" == "" ]; then
    MAKE=make
fi

cd $BASE/sources

env -i PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin \
 $MAKE \
 CC=gcc-4.0 CXX=g++-4.0 \
 ALT_BOOTDIR=$JAVA_HOME \
 JAVA_TOOLS_DIR=$JAVA_HOME/bin \
 ALT_FREETYPE_HEADERS_PATH=/usr/X11R6/include \
 ALT_FREETYPE_LIB_PATH=/usr/X11R6/lib \
 ANT_HOME=/usr/share/ant \
 NO_DOCS=true \
 HOTSPOT_BUILD_JOBS=1
